name: Waka Readme

on:
  schedule:
    # Runs every hour  
    - cron: '0 */1 * * *'
      
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: LalJr/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "FALSE"
          SHOW_PROJECTS: "FALSE"
          SHOW_TIMEZONE: "FALSE"
          SHOW_EDITORS: "TRUE"
          SHOW_LANGUAGE_PER_REPO: "FALSE"
          
